# Generated by Django 6.0.2 on 2026-06-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_comment',
            new_name='blog',
        ),
    ]
