# Generated by Django 6.0.2 on 2026-06-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_post_comment_comment_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_comment',
            new_name='user',
        ),
    ]
